admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

gestor:
    resource: "@gestorBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

logout:
    path: /logout
